### ISSUE TITLE
fifth US Settings

### ISSUE THREAD

**Issue by JonasDaJones** [JonasDaJones/JonasDaJones#6]
## Value Proposition

**As a** developer
**I want to** get the required keys (knobs/ switches) for the form from the "all data",
**so that** the form only shows manipulation possibilities the selected pedal has to offer.
​

## Description

![Image](https://user-images.githubusercontent.com/126177200/248206587-f0f6507d-25e6-4024-a7fa-fdbcb81c2dc7.png)

## Acceptance Criteria

- [ ] Form Shows Input for Knobs and Switches the selected Pedal has.
      ​

## Tasks

- [ ] keeping track about selected pedal using useState
- [ ] map the selected Object (Pedal) for the keys
- [ ] 

      ​

**Comment by julialoeschel** [comment]
Hey.
hier fehlt mir der nutzen für den user.
er kann da etwas eingeben, aber laut der story wird das nirgends gespeichert und angezeigt. 
am besten wäre wenn dir die gespeichteren einstellungen noch irgendwo anzeigen.
